services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - 5432
    volumes:
      - ./postgres/users.sql:/docker-entrypoint-initdb.d/users.sql

  adminer:
    image: adminer:4.8.1
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  node:
    image: "node:20"
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app
    ports:
      - "8081:8081"
    command: bash -c "npm install && npm start"
    environment:
      - PGUSER=root
      - PGPASSWORD=root
      - PGHOST=postgres
      - PGDATABASE=app
      - PGPORT=5432
    depends_on:
      - postgres

  nginx:
    image: nginx:1.26.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - node

  samba:
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./samba:/mount
    environment:
      - USER=app;app
      - SHARE=app;/mount
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
