version: "3.8"

services:
  node:
    image: "node:20"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "8081:8081"
    command: "npm start"

  adminer:
    image: adminer:4.8.1
    ports:
      - "8082:8080"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"
